### PR TITLE
A bunch of copyediting-grammar, spelling.

### PR DESCRIPTION
**Pull request by elvey**
A bunch of improvements.

Except:  I changed the description to
*TINU is the open tool to create bootable macOS installers.*
It ends in a '.' so it should be a sentence.  Or this would be OK:
*TINU, the open tool to create bootable macOS installers*

### CODE REVIEW

**Comment by ITzTravelInTime** [comment]
I see, well i have to confess i am lazy on paperwork and not that great at spelling (since i am not a native english speaker and neither someone who really spent a lot of time learning grammars outside of school), so this contribution is more than welcome.

Also thank you for adding yourself to the credits, but i'd credit you for README copyediting, if that's ok for you, because i like to be more precise.

**Comment by ITzTravelInTime** [comment]
Hi, i have you seen what you have done, thank you very much, since you are interested in helping with the repo, whould you be interested in writing the wiki for TINU?

For what you should do, in case you agree, it is mostly creating some guides (3 of them, more or less) that are about using all the major features of the app and also fixing the writing inside the FAQs page. 

Also you can join TINU's discussion telegram group: https://t.me/TINUBetaTesting

**Comment by elvey** [comment]
You are kind.  My Italian and French are far worse than your English.   I intend to use TINU soonish and if I do, I'll edit the wiki too.  (I avoid commitments I may not meet due to disability issues.  I recall I made a small wiki edit a few days ago - I'm interested.)

**Comment by ITzTravelInTime** [comment]
I need that to be done just in English, since I am Italian and I live in Italy and know plenty of other Italians I can do the Italians stuff by myself, or with the help of people I know irl.

For wiki edits they are ok, perhaps contact me and tell me when and what you want to edit so I know.

Also thank you for contributing, I will also put your name in the app if you want that credit too.

**Pull request merged**
